In [18]:
import os
import numpy as np
from sklearn.datasets import load_svmlight_file
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [19]:
# loadig the dataset
data_file_name= "letter_scale.libsvm"
file_path = os.path.abspath("./Tut02_data/Data/" + data_file_name)
X_data, y_data = load_svmlight_file(file_path)
print(y_data)
X_data = X_data.toarray()
# y_data = y_data.reshape(y_data.shape[0], -1)

[26. 16. 19. ...  1. 12. 22.]


In [24]:
print(X_data[0:2])

[[-0.733333  -0.466667  -0.466667  -0.6       -0.733333  -0.0666667
   0.0666667 -0.733333   0.2        0.466667  -0.0666667 -0.0666667
  -0.866667   0.0666667 -0.333333  -0.2      ]
 [-0.466667  -0.0666667 -0.333333  -0.333333  -0.333333  -0.333333
   0.2       -0.2       -0.466667   0.0666667 -0.0666667  0.2
  -0.733333   0.2       -0.0666667  0.333333 ]]


In [25]:
# split the data into train, valid and test
def train_valid_test_split(data, target, train_size, test_size):
    valid_size = 1 - (train_size + test_size)

    X1, X_test, y1, y_test = train_test_split(data, target, test_size=test_size, random_state = 123)
    X_train, X_valid, y_train, y_valid = train_test_split(X1, y1, test_size=float(valid_size)/(valid_size+ train_size))
    return X_train, X_valid, X_test, y_train, y_valid, y_test

label encoding: categorical labels -> numerical vector

In [26]:
print(y_data)

[26. 16. 19. ...  1. 12. 22.]


In [27]:
le = preprocessing.LabelEncoder()
le.fit(y_data.ravel())
y_data = le.transform(y_data.ravel())
y_data = y_data.ravel()
print(y_data)

[25 15 18 ...  0 11 21]


In [28]:
X_train, X_valid, X_test, y_train, y_valid, y_test = train_valid_test_split(X_data, y_data, train_size=0.8, test_size=0.1)


In [29]:
print(y_train)
print(y_train.reshape(-1))

[22  9 21 ... 20 12 16]
[22  9 21 ... 20 12 16]


In [30]:
print(X_train[0])

[-0.466667   0.0666667 -0.2       -0.2       -0.0666667 -0.0666667
  0.0666667 -0.333333  -0.6       -0.0666667  0.0666667  0.0666667
 -0.333333   0.0666667 -0.6        0.0666667]


In [31]:
from torch.utils.data import Dataset, DataLoader
import torch

In [32]:
class MyDataset(Dataset):
    def __init__(self, data, labels):
        super(MyDataset, self).__init__()
        assert data.shape[0] == labels.shape[0]
        self.data = torch.tensor(data, dtype = torch.float32)
        self.labels = torch.tensor(labels, dtype= torch.float32)
    
    def __len__(self):
        return self.labels.shape[0]
    
    def __getitem__(self, idx):
        return self.data[idx], self.labels[idx]

In [33]:
train_data = MyDataset(X_train, y_train)
valid_data = MyDataset(X_valid, y_valid)
test_data = MyDataset(X_test, y_test)

In [35]:
train_loader = DataLoader(train_data, batch_size=64, shuffle=True)
valid_loader = DataLoader(valid_data, batch_size=64, shuffle=True)
test_loader = DataLoader(test_data, batch_size=64, shuffle=True)

In [41]:
n_features = int(X_train.shape[1])
n_classes = len(np.unique(y_train))
print(n_features)
print(n_classes)

16
26
